import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import Navbar from "@/components/Navbar/Navbar"
import CareFixedLogo from "@/components/CareFixedLogo"
import Header from "@/components/Header"

const geistSans = localFont({
 	src: "./fonts/GeistVF.woff",
  	variable: "--font-geist-sans",
 	 weight: "100 900",
})
const geistMono = localFont({
  	src: "./fonts/GeistMonoVF.woff",
  	variable: "--font-geist-mono",
  	weight: "100 900",
})

export const metadata: Metadata = {
	title: "Create Next App",
  	description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
	<html lang="pt-br">
	  <body
		className={`${geistSans.variable} ${geistMono.variable} antialiased`}
		style={{ paddingTop: '4rem', paddingBottom: '4rem' }}
	  >
		<Header />
		{children}
		<Navbar />
	  </body>
	</html>
  )
}